data_ingestion:
  root_dir: data
  source_url: https://github.com/A-SHI-M/data/raw/refs/heads/main/ecommerce_customer_churn_dataset.zip
  local_data_file: data/ecommerce_customer_churn_dataset.zip
  unzip_dir: data

data_transformation:
  random_seed: 42
  data_raw: data/ecommerce_customer_churn_dataset.csv
  data_processed: data/processed/ecommerce_processed.csv
  models_dir: models
  numerical_features:
    - Age
    - Membership_Years
    - Login_Frequency
    - Session_Duration_Avg
    - Pages_Per_Session
    - Cart_Abandonment_Rate
    - Wishlist_Items
    - Total_Purchases
    - Average_Order_Value
    - Days_Since_Last_Purchase
    - Discount_Usage_Rate
    - Returns_Rate
    - Email_Open_Rate
    - Customer_Service_Calls
    - Product_Reviews_Written
    - Social_Media_Engagement_Score
    - Mobile_App_Usage
    - Payment_Method_Diversity
    - Lifetime_Value
    - Credit_Balance
  engineered_features:
    - Total_Spending
    - Purchase_Frequency
    - RFM_Recency
    - RFM_Frequency
    - RFM_Monetary
    - Customer_Age_Group

model_trainer:
  data_processed: data/processed/ecommerce_processed.csv
  scaler_path: models/scaler.pkl
  model_path: models/kmeans_model.pkl
  artifacts_dir: artifacts
  cluster_profiles_path: artifacts/cluster_profiles.csv
  experiment_name: customer-segmentation

model_evaluation:
  model_path: models/kmeans_model.pkl
  scaler_path: models/scaler.pkl
  data_processed: data/processed/ecommerce_processed.csv
  artifacts_dir: artifacts
  metrics_path: artifacts/evaluation_metrics.json
  experiment_name: customer-segmentation

model_prediction:
  model_path: models/kmeans_model.pkl
  scaler_path: models/scaler.pkl
  predictions_path: artifacts/predictions.csv
